### ISSUE TITLE
Bug(?) when application/rss+xml content, warn_level: :store and html_content_only: true

### ISSUE THREAD

**Issue by dentarg** [jaimeiniesta/metainspector#148]
With `warn_level: :store` and `html_content_only: true`, we get a cryptic error message

```ruby
[26] pry(main)> MetaInspector.new("http://micro.dentarg.net/rss", { warn_level: :store, html_content_only: true }).links.external
NoMethodError: undefined method `search' for #<Array:0x007fada3de1d38>
from /Users/dentarg/.gem/ruby/2.2.3/gems/metainspector-4.7.0/lib/meta_inspector/parsers/links.rb:12:in `raw'
```

Yeah, I know what the README says :-)

> You should avoid using the :store option, or use it wisely, as silencing errors can be problematic, it's always better to face the errors and treat them accordingly.

So maybe I'm on my own here? Or do you consider it a bug in MetaInspector?

Some additional info:

Removing `html_content_only: true`, we get empty array

```ruby
[27] pry(main)> MetaInspector.new("http://micro.dentarg.net/rss", { warn_level: :store }).links.external
=> []
```

Removing `warn_level: :store`, we get a nice error message

```ruby
[29] pry(main)> MetaInspector.new("http://micro.dentarg.net/rss", { html_content_only: true }).links.external
RuntimeError: The url provided contains text/xml content instead of text/html content
from /Users/dentarg/.gem/ruby/2.2.3/gems/metainspector-4.7.0/lib/meta_inspector/document.rb:112:in `document'
```

**Comment by jaimeiniesta** [comment]
Thanks for reporting this!

First of all, be warned that MetaInspector is aimed at parsing HTML documents, not RSS or XML documents. It will, however, be able to extract [some of the info from there](http://metainspectordemo.herokuapp.com/scrape?url=http%3A%2F%2Fmicro.dentarg.net%2Frss), but for things like `links.external` it will not find any, just because that RSS has no `<a>` tag.

So, this is perfectly normal, an empty set is exactly what is found when looking for `<a>` links:

```ruby
> MetaInspector.new("http://micro.dentarg.net/rss").links.external
 => []
```

And exactly the same if you also supply the `warn_level: :store` option, as there is no exception raised:

```ruby
> MetaInspector.new("http://micro.dentarg.net/rss", warn_level: :store).links.external
 => []
```

Now, if you supply the `html_content_only: true` option then it will raise an exception because the content of that document is `text/xml`, that's expected as well:

```ruby
> MetaInspector.new("http://micro.dentarg.net/rss", html_content_only: true).links.external
RuntimeError: The url provided contains text/xml content instead of text/html content
```

But, what is definitely a bug is that, if you pass the `warn_level: :store` option, this exception should be stored, but is failing to do so.

```ruby
> MetaInspector.new("http://micro.dentarg.net/rss", warn_level: :store, html_content_only: true).links.external
NoMethodError: undefined method `search' for #<Array:0x007fd17bb22678>
``` 

I'll have a look!

**Comment by dentarg** [comment]
Thanks!

To be clear, I don't know if the URL I pass to MetaInspector is a HTML document, RSS document, or something else. I'm perfectly fine with getting back `[]` :)

**Comment by jaimeiniesta** [comment]
I thought so, in fact the `html_content_only` option is because of this, when you're spidering you never know what each link is going to return.

I've fixed that, but please read the updated explanation about [Exception handling](https://github.com/jaimeiniesta/metainspector#exception-handling).

The thing is that the `html_content_only` check was done in a lazy way, that is, if you just initialize the document, it won't fail until you start extracting info:

```ruby
p = MetaInspector.new("http://micro.dentarg.net/rss", html_content_only: true, warn_level: :store)
p.ok? # true (it's not OK, but MetaInspector still doesn't know...)
p.links.external # CRASH!
p.ok? # false (I knew it, but it's too late)
```

But now, on 4.7.1...

```ruby
p = MetaInspector.new("http://micro.dentarg.net/rss", html_content_only: true, warn_level: :store)
p.ok? # false
p.exceptions [#<RuntimeError: The url provided contains text/xml content instead of text/html content>, #<NoMethodError: undefined method `match' for [...]:Array>]
```

Which is much better, because when using the exception store, you should proceed with caution and ask for `ok?` before proceeding to the next step if you want to be sure. That is, there's no point in asking for `p.links.external` because the document is not OK, it's not going to work. You should enclose it on a conditional to check for things only if the document is OK.

This is released on 4.7.1, let me know if that works for you!

**Comment by dentarg** [comment]
> because when using the exception store, you should proceed with caution and ask for ok? before proceeding to the next step if you want to be sure. That is, there's no point in asking for p.links.external because the document is not OK, it's not going to work. You should enclose it on a conditional to check for things only if the document is OK.

That's exactly what we do, so the fix will work perfectly. 

Thanks for the fix and the rapid response :)

**Comment by jaimeiniesta** [comment]
Thanks for catching and reporting this! :+1:
