### ISSUE TITLE
Can metainspector login?

### ISSUE THREAD

**Issue by mrjcleaver** [jaimeiniesta/metainspector#156]
Hi - is it possible to provide credentials so metainspector can traverse sites protected by a password?

Thanks, Martin.

**Comment by jaimeiniesta** [comment]
Not currently, but this is an interesting feature that could be added -- and already supported by Faraday, which is what we use to perform the requests.

**Comment by mrjcleaver** [comment]
Interesting, thanks.

Okay, then I guess I would like to be able to register a set of sites, together with their credentials and maybe - ultimately - the path to logging in - so that at an API level I can just say site.login('sitename.whatever.com') and have it login and remain logged in.

**Comment by jaimeiniesta** [comment]
User login can take many different forms, from HTTP Basic authentication, to login through a form with username / password, email / password, or any other combination. Not to mention OAuth and many others...

I think that trying to cover all these kinds of authentication is out of the scope of MetaInspector, I would welcome support for simple authentications like HTTP Basic, but supporting generic authentication can be a daunting task due to the many forms it can take.

Any pull request is welcome, anyway!

**Comment by mrjcleaver** [comment]
How about something using like https://github.com/intridea/omniauth/wiki ?

**Comment by jaimeiniesta** [comment]
Omniauth helps in authenticating using different strategies, for example with external services like Twitter, LinkedIn, Github, etc. But it won't allow you to automate the typical form-based login, where you need to simulate a browser going to a given URL and fill in a form.

**Comment by mrjcleaver** [comment]
Ah, I see; thanks.

So we'd need something that generalized http://crabonature.pl/posts/23-automation-with-mechanize-and-ruby ?

**Comment by jaimeiniesta** [comment]
Exactly, but I see this more like a task for an application, rather than something like a gem like ours could do.

I'll close the issue as I don't see this is a fit for MetaInspector, but feel free to reopen if you have any concrete idea or, better, a pull request! :)
