### ISSUE TITLE
JavaScript Redirects

### ISSUE THREAD

**Issue by haniqassim** [jaimeiniesta/metainspector#160]
I'm trying to scrape pages from this news site in Arabic:
http://www.alarabiya.net/ar/arab-and-world/2015/12/02/-%D9%84%D8%A7%D9%81%D8%B1%D9%88%D9%81-%D9%8A%D9%88%D8%A7%D9%81%D9%82-%D8%B9%D9%84%D9%89-%D9%84%D9%82%D8%A7%D8%A1-%D9%86%D8%B8%D9%8A%D8%B1%D9%87-%D8%A7%D9%84%D8%AA%D8%B1%D9%83%D9%8A-%D9%81%D9%8A-%D8%A8%D9%84%D8%BA%D8%B1%D8%A7%D8%AF.html

I couldn't get anything from it.  When I curl to it, I see JavaScript code which does the redirection.  How can I follow the JS redirection in Metainspector ?

**Comment by gabceb** [comment]
Executing Javascript is not possible in metainspector since all we get is the response from the server as text (note the server redirects does work because the response is to follow the redirect)

To be able to execute javascript you'll need a headless browser like PhantomJS that will indeed contact the server and execute the javascript on it like regular browsers do.
