### ISSUE TITLE
Is there a Javascript equivalent?

### ISSUE THREAD

**Issue by norbertbilbeny** [jaimeiniesta/metainspector#175]
I'm new to github and coding so I almost certainly don't know what I'm talking about but is there a Javascript equivalent of metainspector? I want to retrieve website's title and institutional name from within the browser but not within the domain. For example, I want to, from my site mysite.com, allow users to input a URL, say 

http://www.ft.com/cms/s/2/c2e6b93c-d4fe-11e5-8887-98e7feb46f27.html#slide0

and get back 

(full domain name) Financial Times 
(year of publication) 2016
(title) Britain through the lens of outsiders - FT.com. 

That's what https://www.citethisforme.com does but they don't have a public API and it must be done from within my website.

Thank you.

**Comment by norbertbilbeny** [comment]
Note it must be done from the browser. Server code would not help.

**Comment by gabceb** [comment]
Here is the js equivalent I created https://github.com/gabceb/node-metainspector

Note that doing it from the browser wont work since you'll be blocked by CORS on most sites. Feel free to open issues on the appropiate repo if you have more questions.

**Comment by norbertbilbeny** [comment]
Thanks. Unfortunately it must be from the browser. Server could would not help. An API that does the basics of what citethisforme.com does would work for example. Perhaps there are other solutions too. Any ideas appreciated.

**Comment by gabceb** [comment]
As said before, you won't be able to do it directly from the browser due to CORS. This is a security feature that, believe me, we all want otherwise you'll have random sites you visit making AJAX requests to a page you are logged-in and downloading all your personal information (banks, email providers, etc) since you probably have a cookie that keeps you logged-in.

What citethisforme.com does is have the browser send an AJAX request to another URL on **the same domain** (https://www.citethisforme.com/cite/website/autocite to be more precise) which is why it doesn't have CORS issues and they pass a parameter named `autociteUrl` with the actual url you are trying to cite. Once the server gets the request it parses the site html and returns to the browser the parsed information. How could you figure all this out? Learn how to work with [Chrome devtools](https://developer.chrome.com/devtools) or the equivalent on other browsers and you can reverse-engineer how they sites make things happen.

Happy coding!

**Comment by norbertbilbeny** [comment]
Thanks.

It's pretty remarkable that there are functioning APIs, and have been for years, of book metadata https://www.googleapis.com/books/v1/volumes?q=isbn:0195112768

and academic articles metadata
https://api.crossref.org/works/10.1002/mnfr.200700180

but nothing on websites; not even for the title.

**Comment by norbertbilbeny** [comment]
It would probably take Google seven minutes to build one.
