### ISSUE TITLE
Cannot parsing the site

### ISSUE THREAD

**Issue by eskobar78** [jaimeiniesta/metainspector#219]
https://www.hertz.com
Demo app returns the error:
![demo](https://user-images.githubusercontent.com/9692982/33601154-0dd5c3fa-d9b4-11e7-890f-d84b814d4d9e.jpg)
On irb doesn't find any page:
![irb1](https://user-images.githubusercontent.com/9692982/33601290-6eb25f44-d9b4-11e7-810d-2efd160d311a.jpg)
.......................
![irb2](https://user-images.githubusercontent.com/9692982/33601296-748b0a74-d9b4-11e7-919f-f8580633e9d1.jpg)

**Comment by jaimeiniesta** [comment]
Thanks for the report, but I could scrape it from my development machine. In fact in your screenshot I do see it scrapes the page, it doesn't find any links surely because it's a JS page. Try with `page.title` for example.

In the demo, as it is hosted in heroku, surely they intercept the IP as being an automated request, and they just don't reply, which returns in a timeout.
